### PR TITLE
Add processFn function to process files without

### PR DESCRIPTION
**Pull request by neiltron**
This provides a `processFn` function that will process files without replacing url's of unprocessed files. It's sort of an inverse of `blacklistFn`.

An example use case would be a project where you only want htmlcpr to process specific file types, i.e., images but not stylesheets or scripts.

(It started as `skipFn` but I realized that doesn't really accurately describe what's happening. Hence the branch name.)

### CODE REVIEW

**Comment by korya** [comment]
Thanks. I'll take a look at it later today.

**Comment by korya** [comment]
Sorry for a delay.

The PR looks good except for the name `processFn`. It sounds that this function should provide an alternate logic of processing a single file: process the file if it should be processed, return the new URL. Similar to `LinkTraverser.process()`.

I think when you look from this perspective your first name `skipFn` makes more sense (or at least it sounds less confusing) than `processFn`.

Please, rename it back to `skipFn` or come up with something else. Additionally, do you mind docuemnt the option in README.md?

**Comment by neiltron** [comment]
That makes sense. I've just pushed a change that renames it and documents it in README.md. Let me know if you think it needs more changes.

**Comment by korya** [comment]
Fantastic. Thanks! Merging it and going to bump the version to `v0.0.4`

**Comment by korya** [comment]
OK. `v0.0.4` is published.

Thanks a lot again!

**Pull request merged**
